apiVersion: fission.io/v1
kind: Environment
metadata:
  name: python-nobuilder
  namespace: fission
spec:
  version: 3
  poolsize: 1
  runtime:
    image: ghcr.io/fission/python-env
    container:
      name: python-nobuilder
      port: 8888
  