apiVersion: fission.io/v1
kind: Function
metadata:
  name: websocket-ui-fn
spec:
  environment:
    name: python
    namespace: fission
  
  package:
    packageRef: 
      name: websocket-ui-pkg
      namespace: fission
  
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      executorType: poolmgr
      minScale: 0
      maxScale: 1
