apiVersion: fission.io/v1
kind: Function
metadata:
  name: websocket-ui-fn
spec:
  environment:
    name: python
    namespace: fission
  
  InvokeStrategy:
    executionStrategy:
      executorType: poolmgr
      minScale: 0
      maxScale: 1

  package:
    name: websocket-ui-pkg
  entrypoint: "uvicorn handler:app --host 0.0.0.0 --port 8888"