apiVersion: fission.io/v1
kind: Package
metadata:
  name: websocket-ui-pkg
spec:
  environment:
    name: python
    namespace: fission
  source:
    type: url
    url: https://github.com/DaveWox/fission-functions/archive/refs/heads/main.zip
  buildcmd: "./build.sh"