apiVersion: fission.io/v1
kind: Package
metadata:
  name: hello-world-pkg
  namespace: fission

spec:
  environment:
    name: python-nobuilder
    namespace: fission
    entrypoint: "hello.main"

  deployment:
    checksum: {}
    type: url
    url: "https://raw.githubusercontent.com/DaveWox/fission-functions/main/fission/base/functions/python/hello-world/hello.zip"
